services:
  postgres:
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    privileged: true
    ports:
      - "8000:8000"
      - "40000:40000"
    env_file: e2e.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    volumes:
      - ./certs:/certs
    deploy:
      resources:
        limits:
          memory: 1000m
          cpus: 0.5
