FROM busybox

# Install Nginx. Since busybox httpd doesn't support custom config files easily,
# and installing nginx on busybox is not straightforward,
# we'll use a simpler approach for this test: just serve a static file with busybox httpd.
# This deviates slightly from the original plan of using nginx.conf but simplifies the Dockerfile
# for a basic functionality test.

WORKDIR /usr/share/nginx/html

COPY index.html .

# Expose the port Nginx will run on (or httpd in this case)
EXPOSE 8000

# Command to run Nginx (or httpd)
CMD ["httpd", "-f", "-p", "8000", "-h", "/usr/share/nginx/html"]

