@startuml connect

actor User
participant Backend
participant GitHub
participant Database
participant Secret
participant Pulumi
participant DO as DigitalOcean


User -> Backend: Connect repository request
Backend -> GitHub: Provide OAuth link
GitHub -> User: Return OAuth link

User -> GitHub: Accept OAuth
GitHub -> Backend: OAuth token

Backend -> GitHub: Create webhook on the repository
Backend -> Database: Save connected repository information
@enduml
